apiVersion: v1
kind: ConfigMap
metadata:
  name: hostname-config
  namespace: default
data:
  postgres_host : jdbc:postgresql://10.103.146.19:5432/citizendb?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false