
# For Java 8
FROM openjdk:8-jdk-alpine

# Set the working directory.
WORKDIR /CitizenManagement

ARG JAR_FILE=target/CitizenManagement-0.0.1-SNAPSHOT.jar

COPY ${JAR_FILE} /CitizenManagement/app.jar

EXPOSE 8082/tcp

# java -jar /CitizenManagement/app
ENTRYPOINT ["java","-jar","/CitizenManagement/app.jar"]