apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: requestmanagement
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      name: requestmanagement
      labels:
        app: requestmanagement
    spec:
      containers:
      - name: requestmanagement
        env:
        
          - name: SPRING_DATASOURCE_USERNAME
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: postgres_user
                
          - name: SPRING_DATASOURCE_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: postgres_password

          - name: SPRING_DATASOURCE_URL
            valueFrom:
              configMapKeyRef:
                name: hostname-config
                key: postgres_host    
                
        image:  59911995/requestmanagement:v2
        
---

apiVersion: v1
kind: Service
metadata:
  name: requestsvc
spec:
  type: ClusterIP
  ports:
    - port: 8083
  selector:
    app: requestmanagement