apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: appointmentmanagement
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      name: appointmentmanagement
      labels:
        app: appointmentmanagement
    spec:
      containers:
      - name: appointmentmanagement
        env:
        
          - name: SPRING_DATASOURCE_USERNAME
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: postgres_user
                
          - name: SPRING_DATASOURCE_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: postgres_password

          - name: SPRING_DATASOURCE_URL
            valueFrom:
              configMapKeyRef:
                name: hostname-config
                key: postgres_host    
                
        image:  59911995/appointmentmanagement:v1