apiVersion: v1
kind: ConfigMap
metadata:
  name: hostname-config
  namespace: default
data:
# ###### => kubectl get svc postgres -o jsonpath="{.spec.clusterIP}"
  postgres_host : jdbc:postgresql://########:5432/citizendb?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
