
# For Java 8
FROM openjdk:8-jdk-alpine

# Set the working directory.
WORKDIR /RequestManagement

ARG JAR_FILE=target/RequestManagement-0.0.1-SNAPSHOT.jar

COPY ${JAR_FILE} /RequestManagement/app.jar

EXPOSE 8083/tcp

# java -jar /RequestManagement/app
ENTRYPOINT ["java","-jar","/RequestManagement/app.jar"]